name: ci

run-name: "[${{ github.event.repository.name }}] Check: ${{ github.event_name == 'schedule' && 'scheduled' || github.event.pull_request.title }}"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: "0 21 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
   build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        smalltalk: [ Pharo64-12, Pharo64-13 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Smalltalk CI
        uses: hpi-swa/setup-smalltalkCI@521a156968112c9c7ca094ef78c1287a26665f08 # v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalk.ston
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 15
